### ISSUE TITLE
Django channels example not working

### ISSUE THREAD

**Issue by jwellner** [mirumee/graphql-workshop#4]
I'm trying to get ariadne to work with Django channels but keep failing.

I found this workshop and was hoping this would finally work but I still get the following error:

```
Traceback (most recent call last):
  File "/***/***/.virtualenvs/**/lib/python3.7/site-packages/daphne/http_protocol.py", line 179, in process
    "server": self.server_addr,
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
```

Do you have an idea how to get this to work with ariadne 0.5.0 ?

When I checkout https://github.com/mirumee/graphql-workshop/commit/b83a5f7e23817fc133d9307ceed626349be948ad it looks like its working !

But not with the latest ariadne.
